

--게시판(블로그),공감,회원

--삭제는 생성의 역순으로 진행
DROP TABLE LIKE_T;
DROP TABLE USER_T;
DROP TABLE BOARD_T;

--게시판 테이블
CREATE TABLE BOARD_T (
    BRD_NO      NUMBER  NOT NULL
  , BRD_TITLE   VARCHAR2(100 BYTE) NOT NULL
  , CRTN_DATE   DATE    NOT NULL
  , CONSTRAINT PK_BRD PRIMARY KEY(BRD_NO)
);

--회원 테이블
CREATE TABLE USER_T (
    USER_NO         NUMBER NOT NULL
  , USER_ID         VARCHAR2(32 BYTE) NOT NULL UNIQUE
  , USER_NAME       VARCHAR2(10 BYTE) NOT NULL UNIQUE
  , USER_PHONE      VARCHAR2(13 BYTE) NULL UNIQUE
  , USER_ADDRESS    VARCHAR2(100 BYTE) NULL
  , USER_JUBUN      VARCHAR2(14 BYTE) NULL UNIQUE
  , CONSTRAINT PK_USER PRIMARY KEY(USER_NO)
);

--공감 버튼 테이블
CREATE TABLE LIKE_T (
    LIKE_NO     NUMBER NOT NULL
  , LIKE_COUNT  NUMBER NOT NULL
  , USER_NO     NUMBER NOT NULL
  , BRD_NO      NUMBER NOT NULL
  , CONSTRAINT PK_LIKE PRIMARY KEY(LIKE_NO)
  , CONSTRAINT FK_USER_LIKE FOREIGN KEY(USER_NO) REFERENCES USER_T(USER_NO) ON DELETE SET NULL
  , CONSTRAINT FK_BRD_LIKE FOREIGN KEY(BRD_NO) REFERENCES BOARD_T(BRD_NO) ON DELETE CASCADE
);