--올림픽 데이터베이스 실습

--삭제는 생성의 역순
DROP TABLE SCHEDULE_TBL;
DROP TABLE PLAYER_TBL;
DROP TABLE EVENT_TBL;
DROP TABLE NATION_TBL;


--국가 테이블
CREATE TABLE NATION_TBL (
    N_CODE          NUMBER(3) NOT NULL
  , N_NAME          VARCHAR2(30 BYTE) NOT NULL
  , N_PARTI_PERSON  NUMBER
  , N_PARTI_EVENT   NUMBER
  , N_PREV_RANK     NUMBER
  , N_CURR_RANK     NUMBER
);

--종목 테이블
CREATE TABLE EVENT_TBL (
    E_CODE       NUMBER NOT NULL
  , E_NAME       VARCHAR2(30 BYTE) NOT NULL
  , E_FIRST_YEAR NUMBER(4)
  , E_INFO       VARCHAR2(100 BYTE)
);

--선수 테이블
CREATE TABLE PLAYER_TBL (
    P_CODE NUMBER(3) NOT NULL
  , P_NAME VARCHAR2(30 BYTE) NOT NULL
  , N_CODE NUMBER(3) NOT NULL
  , E_CODE NUMBER NOT NULL
  , P_RANK NUMBER
  , P_AGE  NUMBER(3)
);    
    
--일정 테이블
CREATE TABLE SCHEDULE_TBL (
    S_NO NUMBER(3) NOT NULL
  , N_CODE NUMBER(3)
  , E_CODE NUMBER
  , S_START_DATE DATE
  , S_END_DATE DATE
  , S_INFO VARCHAR2(100 BYTE)
);
--ALTER 이용해서 PK,FK 생성
--기본키 추가하기
ALTER TABLE NATION_TBL ADD CONSTRAINT PK_NATION PRIMARY KEY(N_CODE);
ALTER TABLE EVENT_TBL ADD CONSTRAINT PK_EVENT PRIMARY KEY(E_CODE);
ALTER TABLE PLAYER_TBL ADD CONSTRAINT PK_PLAYER PRIMARY KEY(P_CODE);
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT PK_SCDL PRIMARY KEY(S_NO);

--외래키 추가하기
ALTER TABLE PLAYER_TBL ADD CONSTRAINT FK_NATION_PLAYER FOREIGN KEY(N_CODE) REFERENCES NATION_TBL(N_CODE) ON DELETE CASCADE; -- PLAYER_TBL의 N_CODE가 NOT NULL이므로, ON DELETE SET NULL이 불가능하다.
ALTER TABLE PLAYER_TBL ADD CONSTRAINT FK_EVENT_PLAYER FOREIGN KEY(E_CODE) REFERENCES EVENT_TBL(E_CODE) ON DELETE CASCADE; -- PLAYER_TBL의 E_CODE가 NOT NULL이므로, ON DELETE SET NULL이 불가능하다.

ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_NATION_SCDL FOREIGN KEY(N_CODE) REFERENCES NATION_TBL(N_CODE) ON DELETE SET NULL; -- ON DELETE CASCADE도 가능하다.
ALTER TABLE SCHEDULE_TBL ADD CONSTRAINT FK_EVENT_SCDL FOREIGN KEY(E_CODE) REFERENCES EVENT_TBL(E_CODE) ON DELETE SET NULL; -- ON DELETE CASCADE도 가능하다.
